In [1]:
import sqlite3 
from pathlib import Path

import pandas as pd

# Database exploration

To explore the database

In [2]:
path = "../data/raw/traffic.geodatabase"
db_path = Path(path)
db_path.exists()

conn = sqlite3.connect(db_path)

In [3]:
tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type = 'table';
    """,
    conn
)

# tables

In [4]:
pd.read_sql_query(
   """
   PRAGMA table_info(CRIME_TRAFFICACCIDENTS5YR_P);
   """,
   conn
)

    cid                           name          type  notnull dflt_value  pk
0     0                      object_id       INTEGER        1       None   1
1     1                    incident_id      text(20)        0       None   0
2     2                     offense_id      text(20)        0       None   0
3     3                   offense_code       text(4)        0       None   0
4     4         offense_code_extension       text(4)        0       None   0
5     5   top_traffic_accident_offense      text(30)        0       None   0
6     6          first_occurrence_date      realdate        0       None   0
7     7           last_occurrence_date      realdate        0       None   0
8     8                  reported_date      realdate        0       None   0
9     9               incident_address     text(255)        0       None   0
10   10                          geo_x         int32        0       None   0
11   11                          geo_y         int32        0       None   0
12   12                        geo_lon       float64        0       None   0
13   13                        geo_lat       float64        0       None   0
14   14                    district_id      text(10)        0       None   0
15   15                    precinct_id       text(4)        0       None   0
16   16                neighborhood_id     text(100)        0       None   0
17   17                    bicycle_ind         int32        0       None   0
18   18                 pedestrian_ind         int32        0       None   0
19   19            HARMFUL_EVENT_SEQ_1     text(255)        0       None   0
20   20            HARMFUL_EVENT_SEQ_2     text(255)        0       None   0
21   21            HARMFUL_EVENT_SEQ_3     text(255)        0       None   0
22   22                  road_location     text(255)        0       None   0
23   23               ROAD_DESCRIPTION     text(255)        0       None   0
24   24                   ROAD_CONTOUR     text(255)        0       None   0
25   25                 ROAD_CONDITION     text(255)        0       None   0
26   26                LIGHT_CONDITION     text(255)        0       None   0
27   27               TU1_VEHICLE_TYPE     text(255)        0       None   0
28   28           TU1_TRAVEL_DIRECTION     text(255)        0       None   0
29   29           TU1_VEHICLE_MOVEMENT     text(255)        0       None   0
30   30              TU1_DRIVER_ACTION     text(255)        0       None   0
31   31  TU1_DRIVER_HUMANCONTRIBFACTOR     text(255)        0       None   0
32   32          TU1_PEDESTRIAN_ACTION     text(255)        0       None   0
33   33               TU2_VEHICLE_TYPE     text(255)        0       None   0
34   34           TU2_TRAVEL_DIRECTION     text(255)        0       None   0
35   35           TU2_VEHICLE_MOVEMENT     text(255)        0       None   0
36   36              TU2_DRIVER_ACTION     text(255)        0       None   0
37   37  TU2_DRIVER_HUMANCONTRIBFACTOR     text(255)        0       None   0
38   38          TU2_PEDESTRIAN_ACTION     text(255)        0       None   0
39   39              SERIOUSLY_INJURED         int32        0       None   0
40   40                     FATALITIES         int32        0       None   0
41   41                FATALITY_MODE_1     text(255)        0       None   0
42   42                FATALITY_MODE_2     text(255)        0       None   0
43   43       SERIOUSLY_INJURED_MODE_1     text(255)        0       None   0
44   44       SERIOUSLY_INJURED_MODE_2     text(255)        0       None   0
45   45                        POINT_X       float64        0       None   0
46   46                        POINT_Y       float64        0       None   0
47   47                          SHAPE  geometryblob        0       None   0

In [5]:
pd.read_sql_query(
    """
    SELECT COUNT(*) AS n_rows
    FROM CRIME_TRAFFICACCIDENTS5YR_P;
    """,
    conn
)

   n_rows
0  282358

In [6]:
target_col = "SERIOUSLY_INJURED"
table_name = "CRIME_TRAFFICACCIDENTS5YR_P"

pd.read_sql_query(
    f"""
    SELECT 
        "{target_col}",
        COUNT(*) AS n
    FROM "{table_name}"
    GROUP BY "{target_col}"
    ORDER BY n DESC;
    """,
    conn
)

   SERIOUSLY_INJURED       n
0                0.0  274720
1                1.0    5343
2                NaN    1620
3                2.0     519
4                3.0     111
5                4.0      30
6                5.0      11
7                7.0       2
8                6.0       2