# 2. Cleaning

## Set up

In [1]:
from pathlib import Path
import os

PROJECT_ROOT = Path.cwd().parent

os.chdir(PROJECT_ROOT)
print("Project root:", PROJECT_ROOT)
print("Current working directory:", Path.cwd())

Project root: /Users/Local/REPOSITORIES/injury_risk_classifier
Current working directory: /Users/Local/REPOSITORIES/injury_risk_classifier

In [ ]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from pathlib import Path
import os 

%load_ext autoreload
%autoreload 2

from cleaning_and_features.clean import *

In [3]:
data_path = PROJECT_ROOT / "data" / "interim" / "raw_modeling_data.csv"

df = pd.read_csv(data_path)

## Cleaning

Code for this is in `clean.py`, but I walk through with the dataset

In [4]:
__, miss_report = explore(df, missing = True, threshold= 75)

inspecting data...

There are 282358 rows and 22 columns
There 71 duplicate rows

In [5]:
df = df.drop_duplicates()

In [6]:
print(miss_report)

                              data_types  missing_count  missing_percent  \
top_traffic_accident_offense         str              0             0.00
first_occurrence_date            float64              0             0.00
incident_address                     str              0             0.00
geo_lon                          float64          11155             3.95
geo_lat                          float64          11155             3.95
TU1_DRIVER_ACTION                    str          13423             4.75
TU2_DRIVER_ACTION                    str          15146             5.36
TU1_VEHICLE_TYPE                     str           6849             2.43
TU2_VEHICLE_TYPE                     str          10038             3.56
TU1_DRIVER_HUMANCONTRIBFACTOR        str          15813             5.60
TU2_DRIVER_HUMANCONTRIBFACTOR        str          14182             5.02
TU1_PEDESTRIAN_ACTION                str          77431            27.42
SERIOUSLY_INJURED                float64           1620             0.57
FATALITIES                       float64           1620             0.57
FATALITY_MODE_1                      str          78510            27.81
FATALITY_MODE_2                      str          78671            27.86
SERIOUSLY_INJURED_MODE_1             str          77078            27.30
SERIOUSLY_INJURED_MODE_2             str          78493            27.80
TU2_PEDESTRIAN_ACTION                str          76643            27.14
ROAD_DESCRIPTION                     str            575             0.20
ROAD_CONDITION                       str            750             0.27
LIGHT_CONDITION                      str            663             0.23

                               high missing
top_traffic_accident_offense          False
first_occurrence_date                 False
incident_address                      False
geo_lon                               False
geo_lat                               False
TU1_DRIVER_ACTION                     False
TU2_DRIVER_ACTION                     False
TU1_VEHICLE_TYPE                      False
TU2_VEHICLE_TYPE                      False
TU1_DRIVER_HUMANCONTRIBFACTOR         False
TU2_DRIVER_HUMANCONTRIBFACTOR         False
TU1_PEDESTRIAN_ACTION                 False
SERIOUSLY_INJURED                     False
FATALITIES                            False
FATALITY_MODE_1                       False
FATALITY_MODE_2                       False
SERIOUSLY_INJURED_MODE_1              False
SERIOUSLY_INJURED_MODE_2              False
TU2_PEDESTRIAN_ACTION                 False
ROAD_DESCRIPTION                      False
ROAD_CONDITION                        False
LIGHT_CONDITION                       False

### Date columns

Turns the julian `first_occurance_date` into two columns, time and date

In [7]:
df = split_datetime(df, "first_occurrence_date")

In [8]:
df.head()

,top_traffic_accident_offense,first_occurrence_date,incident_address,geo_lon,geo_lat,TU1_DRIVER_ACTION,TU2_DRIVER_ACTION,TU1_VEHICLE_TYPE,TU2_VEHICLE_TYPE,TU1_DRIVER_HUMANCONTRIBFACTOR,...,FATALITY_MODE_2,SERIOUSLY_INJURED_MODE_1,SERIOUSLY_INJURED_MODE_2,TU2_PEDESTRIAN_ACTION,ROAD_DESCRIPTION,ROAD_CONDITION,LIGHT_CONDITION,datetime,date,time
0,TRAF - ACCIDENT,2.459922e+06,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,No Contributing Action,No Contributing Action,Pickup Truck/Utility Van,Transit Bus,No Apparent Contributing Factor,...,NaN,NaN,NaN,NaN,Non-Intersection,Dry,Daylight,2022-12-09 02:05:59.999991956,2022-12-09,02:05:59
1,TRAF - ACCIDENT,2.459925e+06,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,Failed to Yield ROW,No Contributing Action,Passenger Car/Passenger Van,SUV,No Apparent Contributing Factor,...,NaN,NaN,NaN,NaN,At Intersection,Dry,Daylight,2022-12-11 23:39:59.999991056,2022-12-11,23:39:59
2,TRAF - ACCIDENT,2.459925e+06,I25 HWYSB / PARK AVEW,-104.994972,39.768330,Followed Too Closely,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,No Apparent Contributing Factor,...,NaN,NaN,NaN,NaN,Non-Intersection,Dry,Daylight,2022-12-12 00:10:00.000004471,2022-12-12,00:10:00
3,TRAF - ACCIDENT - POLICE,2.459922e+06,I25 HWYNB / 20TH ST,-105.004334,39.760949,Followed Too Closely,No Contributing Action,Pickup Truck/Utility Van,Passenger Car/Passenger Van,Aggressive Driving,...,NaN,NaN,NaN,NaN,Non-Intersection,Dry,Dark-Lighted,2022-12-09 06:26:59.999983903,2022-12-09,06:26:59
4,TRAF - ACCIDENT - HIT & RUN,2.459922e+06,W 37TH AVE / N PECOS ST,-105.006450,39.768054,NaN,NaN,Unknown (Hit and Run Only),Passenger Car/Passenger Van,NaN,...,NaN,NaN,NaN,NaN,Non-Intersection,Dry,Dark-Lighted,2022-12-09 07:30:00.000000000,2022-12-09,07:30:00

### Text columns

In [9]:
col = ['TU1_VEHICLE_TYPE', 'TU2_VEHICLE_TYPE', 'TU1_DRIVER_ACTION', 'TU2_DRIVER_ACTION', 
       'TU1_DRIVER_HUMANCONTRIBFACTOR', 'TU2_DRIVER_HUMANCONTRIBFACTOR', 
       'TU1_PEDESTRIAN_ACTION', "ROAD_DESCRIPTION", "ROAD_CONDITION", "LIGHT_CONDITION"]

df = clean_text_colummns(df, col)

### Column names

In [10]:
df = clean_column_names(df)

### Create Outcome

In [11]:
df = create_outcome(df)

### Dropping columns

In [12]:
sub = df.loc[:, ["fatality_mode_1", "fatality_mode_2",
            "seriously_injured_mode_1", "seriously_injured_mode_2"]]

In [13]:
__, miss = explore(sub, missing=True)

inspecting data...

There are 282287 rows and 4 columns
There 282081 duplicate rows

In [14]:
print(miss)

                         data_types  missing_count  missing_percent  \
fatality_mode_1                 str          78499            27.81
fatality_mode_2                 str          78660            27.87
seriously_injured_mode_1        str          77068            27.30
seriously_injured_mode_2        str          78482            27.80

                          high missing
fatality_mode_1                  False
fatality_mode_2                  False
seriously_injured_mode_1         False
seriously_injured_mode_2         False

In [15]:
df.drop(columns = ["fatality_mode_1", "fatality_mode_2",
                   "seriously_injured_mode_1", "seriously_injured_mode_2"], inplace = True)

In [16]:
df.head(20)

,top_traffic_accident_offense,first_occurrence_date,incident_address,geo_lon,geo_lat,tu1_driver_action,tu2_driver_action,tu1_vehicle_type,tu2_vehicle_type,tu1_driver_humancontribfactor,...,seriously_injured,fatalities,tu2_pedestrian_action,road_description,road_condition,light_condition,datetime,date,time,injured
0,TRAF - ACCIDENT,2.459922e+06,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,no contributing action,no contributing action,pickup truck/utility van,transit bus,no apparent contributing factor,...,0.0,0.0,NaN,non-intersection,dry,daylight,2022-12-09 02:05:59.999991956,2022-12-09,02:05:59,0
1,TRAF - ACCIDENT,2.459925e+06,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,failed to yield row,no contributing action,passenger car/passenger van,suv,no apparent contributing factor,...,0.0,0.0,NaN,at intersection,dry,daylight,2022-12-11 23:39:59.999991056,2022-12-11,23:39:59,0
2,TRAF - ACCIDENT,2.459925e+06,I25 HWYSB / PARK AVEW,-104.994972,39.768330,followed too closely,no contributing action,passenger car/passenger van,passenger car/passenger van,no apparent contributing factor,...,0.0,0.0,NaN,non-intersection,dry,daylight,2022-12-12 00:10:00.000004471,2022-12-12,00:10:00,0
3,TRAF - ACCIDENT - POLICE,2.459922e+06,I25 HWYNB / 20TH ST,-105.004334,39.760949,followed too closely,no contributing action,pickup truck/utility van,passenger car/passenger van,aggressive driving,...,0.0,0.0,NaN,non-intersection,dry,dark-lighted,2022-12-09 06:26:59.999983903,2022-12-09,06:26:59,0
4,TRAF - ACCIDENT - HIT & RUN,2.459922e+06,W 37TH AVE / N PECOS ST,-105.006450,39.768054,<NA>,<NA>,unknown (hit and run only),passenger car/passenger van,<NA>,...,0.0,0.0,NaN,non-intersection,dry,dark-lighted,2022-12-09 07:30:00.000000000,2022-12-09,07:30:00,0
5,TRAF - ACCIDENT - HIT & RUN,2.459916e+06,S OSCEOLA ST / W BAYAUD AVE,-105.038499,39.714959,careless driving,no contributing action,passenger car/passenger van,passenger car/passenger van,not observed,...,0.0,0.0,NaN,non-intersection,dry,dark-lighted,2022-12-02 14:00:00.000013415,2022-12-02,14:00:00,0
6,TRAF - ACCIDENT - HIT & RUN,2.459916e+06,300 BLOCK E 17TH AVE,-104.983103,39.743008,<NA>,no contributing action,<NA>,passenger car/passenger van,<NA>,...,0.0,0.0,NaN,non-intersection,dry,daylight,2022-12-03 00:20:00.000008943,2022-12-03,00:20:00,0
7,TRAF - ACCIDENT - HIT & RUN,2.459916e+06,N OGDEN ST / E 11TH AVE,-104.975278,39.733689,disregarded stop sign,no contributing action,pickup truck/utility van,passenger car/passenger van,no apparent contributing factor,...,0.0,0.0,NaN,at intersection,dry,dark-lighted,2022-12-03 03:59:59.999986584,2022-12-03,03:59:59,0
8,TRAF - ACCIDENT,2.459916e+06,N CENTRAL PARK BLVD / N VERBENA ST,-104.889926,39.751852,careless driving,lane violation,passenger car/passenger van,passenger car/passenger van,aggressive driving,...,0.0,0.0,NaN,intersection related,dry,daylight,2022-12-03 03:45:00.000000000,2022-12-03,03:45:00,0
9,TRAF - ACCIDENT - HIT & RUN,2.459916e+06,I70 HWYWB / N NORTHFIELD QUEBEC ST,-104.903436,39.778421,lane violation,no contributing action,passenger car/passenger van,passenger car/passenger van,not observed,...,0.0,0.0,NaN,intersection related,dry,dark-lighted,2022-12-03 07:29:00.000003572,2022-12-03,07:29:00,0
10,TRAF - ACCIDENT - HIT & RUN,2.459922e+06,E 17TH AVE / N YOSEMITE ST,-104.884655,39.743783,followed too closely,no contributing action,<NA>,passenger car/passenger van,not observed,...,0.0,0.0,NaN,non-intersection,dry,dawn or dusk,2022-12-09 05:13:00.000007152,2022-12-09,05:13:00,0
11,TRAF - ACCIDENT,2.459955e+06,S QUEBEC ST / E CHERRY CREEK S DR,-104.903509,39.684900,followed too closely,no contributing action,passenger car/passenger van,passenger car/passenger van,aggressive driving,...,0.0,0.0,NaN,at intersection,dry,daylight,2023-01-11 03:45:00.000000000,2023-01-11,03:45:00,0
12,TRAF - ACCIDENT - HIT & RUN,2.459916e+06,W 13TH AVE / N SPEER BLVD,-104.996475,39.736862,careless driving,no contributing action,working vehicle/equipment,other vehicle type (describe in narative),aggressive driving,...,0.0,0.0,NaN,non-intersection,dry,dark-lighted,2022-12-03 06:07:00.000015196,2022-12-03,06:07:00,0
13,TRAF - ACCIDENT,2.459930e+06,1801 WEWATTA ST,-104.999962,39.755423,no contributing action,<NA>,pickup truck/utility van,<NA>,no apparent contributing factor,...,0.0,0.0,NaN,parking lot,dry,dark-lighted,2022-12-17 05:57:00.000010725,2022-12-17,05:57:00,0
14,TRAF - ACCIDENT - HIT & RUN,2.459955e+06,3144 N UMATILLA ST,-105.011670,39.761685,careless driving,<NA>,passenger car/passenger van,<NA>,<NA>,...,0.0,0.0,NaN,alley related,icy,daylight,2023-01-11 03:59:59.999986584,2023-01-11,03:59:59,0
15,TRAF - ACCIDENT - HIT & RUN,2.459929e+06,E 53RD AVE / N CHAMBERS RD,-104.809755,39.790353,careless driving,no contributing action,passenger car/passenger van,passenger car/passenger van,aggressive driving,...,0.0,0.0,NaN,at intersection,dry,dark-lighted,2022-12-16 05:13:00.000007152,2022-12-16,05:13:00,0
16,TRAF - ACCIDENT - HIT & RUN,2.459929e+06,4547 E 16TH AVE,-104.934277,39.741633,under investigation,under investigation,under investigation,under investigation,under investigation,...,NaN,NaN,UNDER INVESTIGATION,under investigation,under investigation,under investigation,2022-12-16 05:16:59.999992847,2022-12-16,05:16:59,0
17,TRAF - ACCIDENT - HIT & RUN,2.459923e+06,300 S FEDERAL BLVD,-105.024750,39.710693,under investigation,under investigation,under investigation,under investigation,under investigation,...,NaN,NaN,UNDER INVESTIGATION,under investigation,under investigation,under investigation,2022-12-10 08:29:59.999986584,2022-12-10,08:29:59,0
18,TRAF - ACCIDENT,2.459929e+06,"LAT:39°43'44.74""N LONG:104°58'39.34""W W 8TH AV...",-104.977595,39.729095,failed to yield row,<NA>,passenger car/passenger van,<NA>,looked/did not see,...,0.0,0.0,Cross/Enter at Intersection,at intersection,dry,dark-lighted,2022-12-16 06:27:59.999980331,2022-12-16,06:27:59,0
19,TRAF - ACCIDENT - HIT & RUN,2.459930e+06,W 44TH AVE / N JULIAN ST,-105.031084,39.776695,careless driving,<NA>,suv,passenger car/passenger van,aggressive driving,...,0.0,0.0,NaN,non-intersection,dry,dark-lighted,2022-12-17 09:30:00.000013415,2022-12-17,09:30:00,0

## Recoding

The following cells recode the messy text columns to understand the columns and combine classes. For example, distracted coveres "distracted-other", "distracted/other interior", "distracted/other exterior". 

This is completed for the following sets of columns 

| Information | Column names | Descrip. |  Example|
| -------- | -------- | -------- | -------- |
| vehicle_type | `tu1_vehicle_type`, `tu2_vehicle_type` | Vehicle Type |  "passenger", "vehicle over 10000 lbs" |
| driver actions | `tu1_driver_action`, `tu2_driver_action` | Driver actions, specifically in vehicle operation | "failure to yeild" |
| human factor | `tu1_driver_humancontribfactor`, `tu2_driver_humancontribfactor` | Driver actions, not directly in vehicle movement | "distracted", "medical" |

For each pair of columns, I 
1. count how often each entry appears per column (`create_types_table`)
2. combine related entries (`bin_`) 
3. try to understand how many of each accident type, based on binned columns, were injurious.

### Vehicle Types

In [17]:
vehicle_types = create_types_tables(
    df,
    "tu1_vehicle_type",
    "tu2_vehicle_type",
    first_label="first_vehicle_type",
    second_label="second_vehicle_type"
)

vehicle_types

,first_vehicle_type,second_vehicle_type,total
passenger car/van,96818,97346,194164
suv,59399,64388,123787
passenger car/passenger van,34815,37401,72216
pickup truck/utility van,31487,28162,59649
other,8104,16253,24357
<NA>,6849,10037,16886
hit and run unknown,14702,483,15185
,2130,8946,11076
vehicle over 10000 lbs,6324,4630,10954
pickup truck/utility van with trailier,4680,3866,8546
unknown (hit and run only),6641,180,6821
motorcycle,1925,1921,3846
under investigation,1617,1617,3234
transit bus,1196,1614,2810
bicycle,1129,1319,2448
"medium/heavy trucks gvwr/gcwr 16,001 and over",1344,1076,2420
"medium/heavy trucks gvwr/gcwr between 10,001 and 16,000",648,513,1161
non-school bus,454,559,1013
passenger car/van with trailer,361,415,776
other vehicle type (describe in narative),356,317,673
school bus,277,295,572
suv with trailer,178,165,343
working vehicle/equipment,166,171,337
motor home,221,101,322
non-school bus (9 occupants or more including driver) in commerce,110,152,262
motorized bicycle,92,80,172
school bus (all school buses),83,77,160
light rail,27,99,126
autocycle,63,41,104
low speed vehicle,36,27,63
farm equipment,30,19,49
off highway vehicle/atv,23,4,27
heavy train,0,12,12
0,1,0,1
snowmobile,0,1,1
unk,1,0,1

In [18]:
df["tu1_vehicle_type_binned"] = df["tu1_vehicle_type"].apply(bin_vehicle_type)
df["tu2_vehicle_type_binned"] = df["tu2_vehicle_type"].apply(bin_vehicle_type)

In [19]:
accident_summary_wrt(df, col= "tu1_vehicle_type_binned")

                               count      mean
tu1_vehicle_type_binned
motorcycle_or_autocycle         1988  0.348592
bicycle_or_motorized_bicycle    1221  0.156429
other                           8460  0.058156
equipment_or_special_vehicle     255  0.054902
passenger_car_or_van          131994  0.021933
suv                            59577  0.019722
pickup_or_utility_van          36167  0.018221
heavy_truck                     8316  0.012145
bus                             2120  0.010849
unknown                        31941  0.009424
motor_home                       221  0.004525
rail                              27  0.000000

### Driver actions

In [20]:
driver_action = create_types_tables(
    df,
    "tu1_driver_action",
    "tu2_driver_action",
    first_label="first_driver_action",
    second_label="first_driver_action"
)

driver_action

                                        first_driver_action   total
tu2_driver_action
other                                                 91523  183046
no action                                             63197  126394
no contributing action                                61369  122738
00                                                    29025   58050
<NA>                                                  15145   30290
                                                      14136   28272
under investigation                                    1617    3234
lane violation                                         1106    2212
followed too closely                                    969    1938
careless driving                                        873    1746
other contributing action                               820    1640
exceed safe/posted speed                                624    1248
failed to yield row                                     545    1090
failed to stop at signal                                296     592
improper backing                                        171     342
impeded traffic                                         134     268
improper turn                                           132     264
reckless driving                                         94     188
improper passing on left                                 74     148
speeding                                                 70     140
turned from wrong lane or position                       53     106
over-correcting/over-steering                            46      92
signaling violation                                      41      82
too fast for conditions                                  40      80
improper passing on right                                39      78
other improper turns                                     38      76
disregarded other device                                 34      68
disregard stop sign                                      28      56
disregarded other device/sign/markings                   23      46
disregarded stop sign                                    17      34
racing                                                    3       6
0                                                         2       4
-                                                         1       2
non                                                       1       2
none                                                      1       2

In [21]:
df["tu1_driver_action_binned"] = (df["tu1_driver_action"].apply(bin_driver_action))
df["tu2_driver_action_binned"] = (df["tu2_driver_action"].apply(bin_driver_action))

In [22]:
accident_summary_wrt(df, col= "tu1_driver_action_binned")

                           count      mean
tu1_driver_action_binned
traffic_flow                 323  0.043344
failure_to_obey            15110  0.036400
speed_related               5023  0.030460
failure_to_yield           27769  0.029097
aggressive_or_careless    104774  0.028986
other                      53777  0.022314
no_action                  14694  0.015448
unknown                    20828  0.012099
lane_or_position           26150  0.008298
turning_or_backing         13839  0.006287

### Human contributing factor

In [23]:
human_factor = create_types_tables(
    df,
    "tu1_driver_humancontribfactor",
    "tu2_driver_humancontribfactor",
    first_label="first_driver",
    second_label="second_driver"
)

human_factor

                                         first_driver  second_driver   total
no apparent                                     78474         158518  236992
no apparent contributing factor                 16372          60315   76687
other                                           37660          26067   63727
<NA>                                            15813          14181   29994
aggressive driving                              23841            912   24753
                                                 8808          15310   24118
distracted-other                                16721            324   17045
driver inexperience                             15977            525   16502
not observed                                    12798           2813   15611
dui/dwai/duid                                   10710            186   10896
driver unfamiliar with area                      9070            216    9286
looked/did not see                               8490            358    8848
other factor                                     4170            500    4670
distracted/other interior                        4403             29    4432
under investigation                              1617           1617    3234
distracted cellphone                             2815             41    2856
distracted/other exterior                        2161             47    2208
age/driver ability                               1805             72    1877
distracted passenger                             1616             42    1658
driver fatigue                                   1398             25    1423
illness/medical                                  1159              6    1165
asleep at the wheel                              1035             83    1118
evading law enforcement officer                   798              7     805
driver emotionally upset                          759             44     803
asleep or fatigued                                792              7     799
distracted radio                                  537              5     542
distracted/other occupant                         441              2     443
physical disability                               400              6     406
sun glare                                         354             17     371
medical                                           355              4     359
distracted/manipulating vehicle control           346              3     349
distracted eating/drinking                        188              1     189
manipulating electronic device                    177              1     178
talking on phone/holding                          118              2     120
illness                                            67              0      67
distracted/smoking                                 29              0      29
talking on phone/hands free                         9              0       9
00                                                  1              1       2
18                                                  1              0       1
17                                                  1              0       1
06                                                  1              0       1

In [24]:
df['tu1_human_factor_binned'] = (df["tu1_driver_humancontribfactor"]
                        .apply(bin_human_contrib_factor))

df['tu2_human_factor_binned'] = (df["tu2_driver_humancontribfactor"]
                        .apply(bin_human_contrib_factor))

In [25]:
accident_summary_wrt(df, col= "tu1_human_factor_binned")

                            count      mean
tu1_human_factor_binned
medical_or_ability           3786  0.061014
impairment                  10710  0.056489
aggressive_or_evading       24639  0.043184
environmental_visibility      354  0.031073
fatigue_or_sleep             3225  0.029457
other                       41830  0.026584
emotional                     759  0.023715
inexperience_or_unfamiliar  25047  0.021280
distracted                  34932  0.019953
phone_or_device              3119  0.018916
unknown                     39039  0.016419
no_apparent                 94847  0.015594

Among the 3,787 crashes where driver 1 had a medical/ability-related contributing factor, about 6.1% resulted in injury/fatality.

However, this does not mean the medical factors caused the accident or caused the accident top be injurious. Of the crashed that could be categorized, 6% involved injury.

In [26]:
df.drop(columns = ["tu1_driver_action", "tu2_driver_action",
                   "tu1_vehicle_type", "tu2_vehicle_type",
                   'tu1_driver_humancontribfactor',
                   'tu2_driver_humancontribfactor',
                   'tu1_pedestrian_action',
                   'tu2_pedestrian_action',
                   "seriously_injured",
                   "fatalities"], inplace=True)

df = df.rename(columns= {
    "geo_lon" : "lon",
    "geo_lat" : 'lat'
})

In [27]:
df.head(25)

,top_traffic_accident_offense,first_occurrence_date,incident_address,lon,lat,road_description,road_condition,light_condition,datetime,date,time,injured,tu1_vehicle_type_binned,tu2_vehicle_type_binned,tu1_driver_action_binned,tu2_driver_action_binned,tu1_human_factor_binned,tu2_human_factor_binned
0,TRAF - ACCIDENT,2.459922e+06,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,non-intersection,dry,daylight,2022-12-09 02:05:59.999991956,2022-12-09,02:05:59,0,pickup_or_utility_van,bus,no_action,no_action,no_apparent,no_apparent
1,TRAF - ACCIDENT,2.459925e+06,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,at intersection,dry,daylight,2022-12-11 23:39:59.999991056,2022-12-11,23:39:59,0,passenger_car_or_van,suv,failure_to_yield,no_action,no_apparent,no_apparent
2,TRAF - ACCIDENT,2.459925e+06,I25 HWYSB / PARK AVEW,-104.994972,39.768330,non-intersection,dry,daylight,2022-12-12 00:10:00.000004471,2022-12-12,00:10:00,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,no_apparent,no_apparent
3,TRAF - ACCIDENT - POLICE,2.459922e+06,I25 HWYNB / 20TH ST,-105.004334,39.760949,non-intersection,dry,dark-lighted,2022-12-09 06:26:59.999983903,2022-12-09,06:26:59,0,pickup_or_utility_van,passenger_car_or_van,aggressive_or_careless,no_action,aggressive_or_evading,no_apparent
4,TRAF - ACCIDENT - HIT & RUN,2.459922e+06,W 37TH AVE / N PECOS ST,-105.006450,39.768054,non-intersection,dry,dark-lighted,2022-12-09 07:30:00.000000000,2022-12-09,07:30:00,0,unknown,passenger_car_or_van,unknown,unknown,unknown,unknown
5,TRAF - ACCIDENT - HIT & RUN,2.459916e+06,S OSCEOLA ST / W BAYAUD AVE,-105.038499,39.714959,non-intersection,dry,dark-lighted,2022-12-02 14:00:00.000013415,2022-12-02,14:00:00,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,unknown,no_apparent
6,TRAF - ACCIDENT - HIT & RUN,2.459916e+06,300 BLOCK E 17TH AVE,-104.983103,39.743008,non-intersection,dry,daylight,2022-12-03 00:20:00.000008943,2022-12-03,00:20:00,0,unknown,passenger_car_or_van,unknown,no_action,unknown,no_apparent
7,TRAF - ACCIDENT - HIT & RUN,2.459916e+06,N OGDEN ST / E 11TH AVE,-104.975278,39.733689,at intersection,dry,dark-lighted,2022-12-03 03:59:59.999986584,2022-12-03,03:59:59,0,pickup_or_utility_van,passenger_car_or_van,failure_to_obey,no_action,no_apparent,no_apparent
8,TRAF - ACCIDENT,2.459916e+06,N CENTRAL PARK BLVD / N VERBENA ST,-104.889926,39.751852,intersection related,dry,daylight,2022-12-03 03:45:00.000000000,2022-12-03,03:45:00,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,lane_or_position,aggressive_or_evading,aggressive_or_evading
9,TRAF - ACCIDENT - HIT & RUN,2.459916e+06,I70 HWYWB / N NORTHFIELD QUEBEC ST,-104.903436,39.778421,intersection related,dry,dark-lighted,2022-12-03 07:29:00.000003572,2022-12-03,07:29:00,0,passenger_car_or_van,passenger_car_or_van,lane_or_position,no_action,unknown,no_apparent
10,TRAF - ACCIDENT - HIT & RUN,2.459922e+06,E 17TH AVE / N YOSEMITE ST,-104.884655,39.743783,non-intersection,dry,dawn or dusk,2022-12-09 05:13:00.000007152,2022-12-09,05:13:00,0,unknown,passenger_car_or_van,aggressive_or_careless,no_action,unknown,unknown
11,TRAF - ACCIDENT,2.459955e+06,S QUEBEC ST / E CHERRY CREEK S DR,-104.903509,39.684900,at intersection,dry,daylight,2023-01-11 03:45:00.000000000,2023-01-11,03:45:00,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,aggressive_or_evading,no_apparent
12,TRAF - ACCIDENT - HIT & RUN,2.459916e+06,W 13TH AVE / N SPEER BLVD,-104.996475,39.736862,non-intersection,dry,dark-lighted,2022-12-03 06:07:00.000015196,2022-12-03,06:07:00,0,equipment_or_special_vehicle,other,aggressive_or_careless,no_action,aggressive_or_evading,no_apparent
13,TRAF - ACCIDENT,2.459930e+06,1801 WEWATTA ST,-104.999962,39.755423,parking lot,dry,dark-lighted,2022-12-17 05:57:00.000010725,2022-12-17,05:57:00,0,pickup_or_utility_van,unknown,no_action,unknown,no_apparent,unknown
14,TRAF - ACCIDENT - HIT & RUN,2.459955e+06,3144 N UMATILLA ST,-105.011670,39.761685,alley related,icy,daylight,2023-01-11 03:59:59.999986584,2023-01-11,03:59:59,0,passenger_car_or_van,unknown,aggressive_or_careless,unknown,unknown,unknown
15,TRAF - ACCIDENT - HIT & RUN,2.459929e+06,E 53RD AVE / N CHAMBERS RD,-104.809755,39.790353,at intersection,dry,dark-lighted,2022-12-16 05:13:00.000007152,2022-12-16,05:13:00,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,aggressive_or_evading,no_apparent
16,TRAF - ACCIDENT - HIT & RUN,2.459929e+06,4547 E 16TH AVE,-104.934277,39.741633,under investigation,under investigation,under investigation,2022-12-16 05:16:59.999992847,2022-12-16,05:16:59,0,unknown,unknown,unknown,unknown,unknown,unknown
17,TRAF - ACCIDENT - HIT & RUN,2.459923e+06,300 S FEDERAL BLVD,-105.024750,39.710693,under investigation,under investigation,under investigation,2022-12-10 08:29:59.999986584,2022-12-10,08:29:59,0,unknown,unknown,unknown,unknown,unknown,unknown
18,TRAF - ACCIDENT,2.459929e+06,"LAT:39°43'44.74""N LONG:104°58'39.34""W W 8TH AV...",-104.977595,39.729095,at intersection,dry,dark-lighted,2022-12-16 06:27:59.999980331,2022-12-16,06:27:59,0,passenger_car_or_van,unknown,failure_to_yield,unknown,distracted,unknown
19,TRAF - ACCIDENT - HIT & RUN,2.459930e+06,W 44TH AVE / N JULIAN ST,-105.031084,39.776695,non-intersection,dry,dark-lighted,2022-12-17 09:30:00.000013415,2022-12-17,09:30:00,0,suv,passenger_car_or_van,aggressive_or_careless,unknown,aggressive_or_evading,unknown
20,TRAF - ACCIDENT,2.459952e+06,E ALAMEDA AVE / S LINCOLN ST,-104.986369,39.711158,at intersection,dry,daylight,2023-01-07 21:26:59.999983903,2023-01-07,21:26:59,0,passenger_car_or_van,passenger_car_or_van,failure_to_obey,no_action,aggressive_or_evading,no_apparent
21,TRAF - ACCIDENT - HIT & RUN,2.459952e+06,1600 BLOCK S BROADWAY ST,-104.987353,39.687462,non-intersection,dry,dawn or dusk,2023-01-07 17:48:00.000002681,2023-01-07,17:48:00,0,suv,suv,aggressive_or_careless,no_action,aggressive_or_evading,no_apparent
22,TRAF - ACCIDENT,2.460922e+06,E 8TH AVE / N MONACO ST,-104.912796,39.729278,at intersection,dry,daylight,2025-09-03 21:11:59.999997318,2025-09-03,21:11:59,0,passenger_car_or_van,suv,lane_or_position,no_action,unknown,no_apparent
23,TRAF - ACCIDENT - DUI/DUID,2.461023e+06,2700 BLOCK S GREEN CT,-105.025963,39.666381,non-intersection,dry,dark-lighted,2025-12-13 16:27:00.000010725,2025-12-13,16:27:00,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,fatigue_or_sleep,no_apparent
24,TRAF - ACCIDENT - DUI/DUID,2.460921e+06,W YALE AVE / S RALEIGH ST,-105.041755,39.667717,non-intersection,dry,daylight,2025-09-03 04:06:00.000005362,2025-09-03,04:06:00,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,no_apparent,no_apparent

In [28]:
df.to_csv("data/interim/traffic_clean.csv", index = False)