# 2. Cleaning

## Set up

In [2]:
from pathlib import Path
import os

PROJECT_ROOT = Path.cwd().parent

os.chdir(PROJECT_ROOT)
print("Project root:", PROJECT_ROOT)
print("Current working directory:", Path.cwd())

Project root: /Users/Local/REPOSITORIES/injury_risk_classifier
Current working directory: /Users/Local/REPOSITORIES/injury_risk_classifier

In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from pathlib import Path
import os 

%load_ext autoreload
%autoreload 2

from src.clean import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
data_path = PROJECT_ROOT / "data" / "interim" / "raw_modeling_data.csv"

df = pd.read_csv(data_path)

## Cleaning

Code for this is in `clean.py`, but I walk through with the dataset

In [5]:
__, miss_report = explore(df, missing = True, threshold= 75)

inspecting data...

There are 282358 rows and 22 columns
There 71 duplicate rows

In [6]:
print(miss_report)

                              data_types  missing_count  missing_percent  \
top_traffic_accident_offense         str              0             0.00
first_occurrence_date            float64              0             0.00
incident_address                     str              0             0.00
geo_lon                          float64          11155             3.95
geo_lat                          float64          11155             3.95
TU1_DRIVER_ACTION                    str          13423             4.75
TU2_DRIVER_ACTION                    str          15146             5.36
TU1_VEHICLE_TYPE                     str           6849             2.43
TU2_VEHICLE_TYPE                     str          10038             3.56
TU1_DRIVER_HUMANCONTRIBFACTOR        str          15813             5.60
TU2_DRIVER_HUMANCONTRIBFACTOR        str          14182             5.02
TU1_PEDESTRIAN_ACTION                str          77431            27.42
SERIOUSLY_INJURED                float64           1620             0.57
FATALITIES                       float64           1620             0.57
FATALITY_MODE_1                      str          78510            27.81
FATALITY_MODE_2                      str          78671            27.86
SERIOUSLY_INJURED_MODE_1             str          77078            27.30
SERIOUSLY_INJURED_MODE_2             str          78493            27.80
TU2_PEDESTRIAN_ACTION                str          76643            27.14
ROAD_DESCRIPTION                     str            575             0.20
ROAD_CONDITION                       str            750             0.27
LIGHT_CONDITION                      str            663             0.23

                               high missing
top_traffic_accident_offense          False
first_occurrence_date                 False
incident_address                      False
geo_lon                               False
geo_lat                               False
TU1_DRIVER_ACTION                     False
TU2_DRIVER_ACTION                     False
TU1_VEHICLE_TYPE                      False
TU2_VEHICLE_TYPE                      False
TU1_DRIVER_HUMANCONTRIBFACTOR         False
TU2_DRIVER_HUMANCONTRIBFACTOR         False
TU1_PEDESTRIAN_ACTION                 False
SERIOUSLY_INJURED                     False
FATALITIES                            False
FATALITY_MODE_1                       False
FATALITY_MODE_2                       False
SERIOUSLY_INJURED_MODE_1              False
SERIOUSLY_INJURED_MODE_2              False
TU2_PEDESTRIAN_ACTION                 False
ROAD_DESCRIPTION                      False
ROAD_CONDITION                        False
LIGHT_CONDITION                       False

### Date columns

Turns the julian `first_occurance_date` into two columns, time and date

In [7]:
split_datetime(df, df["first_occurrence_date"])

,top_traffic_accident_offense,first_occurrence_date,incident_address,geo_lon,geo_lat,TU1_DRIVER_ACTION,TU2_DRIVER_ACTION,TU1_VEHICLE_TYPE,TU2_VEHICLE_TYPE,TU1_DRIVER_HUMANCONTRIBFACTOR,...,FATALITY_MODE_1,FATALITY_MODE_2,SERIOUSLY_INJURED_MODE_1,SERIOUSLY_INJURED_MODE_2,TU2_PEDESTRIAN_ACTION,ROAD_DESCRIPTION,ROAD_CONDITION,LIGHT_CONDITION,date,time
0,TRAF - ACCIDENT,2.459922e+06,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,No Contributing Action,No Contributing Action,Pickup Truck/Utility Van,Transit Bus,No Apparent Contributing Factor,...,NaN,NaN,NaN,NaN,NaN,Non-Intersection,Dry,Daylight,2022-12-08,14:05:59
1,TRAF - ACCIDENT,2.459925e+06,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,Failed to Yield ROW,No Contributing Action,Passenger Car/Passenger Van,SUV,No Apparent Contributing Factor,...,NaN,NaN,NaN,NaN,NaN,At Intersection,Dry,Daylight,2022-12-11,11:39:59
2,TRAF - ACCIDENT,2.459925e+06,I25 HWYSB / PARK AVEW,-104.994972,39.768330,Followed Too Closely,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,No Apparent Contributing Factor,...,NaN,NaN,NaN,NaN,NaN,Non-Intersection,Dry,Daylight,2022-12-11,12:10:00
3,TRAF - ACCIDENT - POLICE,2.459922e+06,I25 HWYNB / 20TH ST,-105.004334,39.760949,Followed Too Closely,No Contributing Action,Pickup Truck/Utility Van,Passenger Car/Passenger Van,Aggressive Driving,...,NaN,NaN,NaN,NaN,NaN,Non-Intersection,Dry,Dark-Lighted,2022-12-08,18:26:59
4,TRAF - ACCIDENT - HIT & RUN,2.459922e+06,W 37TH AVE / N PECOS ST,-105.006450,39.768054,NaN,NaN,Unknown (Hit and Run Only),Passenger Car/Passenger Van,NaN,...,NaN,NaN,NaN,NaN,NaN,Non-Intersection,Dry,Dark-Lighted,2022-12-08,19:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282353,TRAF - ACCIDENT,2.459920e+06,I25 HWYSB / W 23RD AVE,-105.016793,39.751285,Lane Violation,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,Distracted/Other Interior,...,NaN,NaN,NaN,NaN,NaN,At Intersection,Dry,Daylight,2022-12-06,08:00:00
282354,TRAF - ACCIDENT - HIT & RUN,2.459942e+06,I70 HWYWB / N MONACO ST,-104.912882,39.778408,Careless Driving,No Contributing Action,SUV,Pickup Truck/Utility Van,Aggressive Driving,...,NaN,NaN,NaN,NaN,NaN,Non-Intersection,Dry,Daylight,2022-12-28,14:15:00
282355,TRAF - ACCIDENT,2.459942e+06,50 BLOCK N HOLLY ST,-104.922176,39.717045,Followed Too Closely,No Contributing Action,Passenger Car/Passenger Van,Pickup Truck/Utility Van,No Apparent Contributing Factor,...,NaN,NaN,NaN,NaN,NaN,Non-Intersection,Wet,Daylight,2022-12-28,14:29:59
282356,TRAF - ACCIDENT - HIT & RUN,2.459945e+06,20TH ST / ARAPAHOE ST,-104.990832,39.751590,Lane Violation,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,No Apparent Contributing Factor,...,NaN,NaN,NaN,NaN,NaN,At Intersection,Dry,Dark-Lighted,2022-12-31,02:00:00
282357,TRAF - ACCIDENT - HIT & RUN,2.459944e+06,5190 N GRAY ST,-105.060105,39.790885,Too Fast for Conditions,NaN,Unknown (Hit and Run Only),NaN,No Apparent Contributing Factor,...,NaN,NaN,NaN,NaN,NaN,Non-Intersection,Icy W/Visible Icy Road Treatment,Daylight,2022-12-30,09:00:00

### Column names

In [8]:
df = clean_column_names(df)

### Dropping columns

In [9]:
sub = df.loc[:, ["fatality_mode_1", "fatality_mode_2",
            "seriously_injured_mode_1", "seriously_injured_mode_2"]]

In [10]:
__, miss = explore(sub, missing=True)

inspecting data...

There are 282358 rows and 4 columns
There 282152 duplicate rows

In [11]:
print(miss)

                         data_types  missing_count  missing_percent  \
fatality_mode_1                 str          78510            27.81
fatality_mode_2                 str          78671            27.86
seriously_injured_mode_1        str          77078            27.30
seriously_injured_mode_2        str          78493            27.80

                          high missing
fatality_mode_1                  False
fatality_mode_2                  False
seriously_injured_mode_1         False
seriously_injured_mode_2         False

In [12]:
df.drop(columns = ["first_occurrence_date",
                   "fatality_mode_1", "fatality_mode_2",
                   "seriously_injured_mode_1", "seriously_injured_mode_2"], inplace = True)

In [13]:
df.head(20)

,top_traffic_accident_offense,incident_address,geo_lon,geo_lat,tu1_driver_action,tu2_driver_action,tu1_vehicle_type,tu2_vehicle_type,tu1_driver_humancontribfactor,tu2_driver_humancontribfactor,tu1_pedestrian_action,seriously_injured,fatalities,tu2_pedestrian_action,road_description,road_condition,light_condition
0,TRAF - ACCIDENT,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,No Contributing Action,No Contributing Action,Pickup Truck/Utility Van,Transit Bus,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight
1,TRAF - ACCIDENT,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,Failed to Yield ROW,No Contributing Action,Passenger Car/Passenger Van,SUV,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,At Intersection,Dry,Daylight
2,TRAF - ACCIDENT,I25 HWYSB / PARK AVEW,-104.994972,39.768330,Followed Too Closely,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight
3,TRAF - ACCIDENT - POLICE,I25 HWYNB / 20TH ST,-105.004334,39.760949,Followed Too Closely,No Contributing Action,Pickup Truck/Utility Van,Passenger Car/Passenger Van,Aggressive Driving,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted
4,TRAF - ACCIDENT - HIT & RUN,W 37TH AVE / N PECOS ST,-105.006450,39.768054,NaN,NaN,Unknown (Hit and Run Only),Passenger Car/Passenger Van,NaN,NaN,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted
5,TRAF - ACCIDENT - HIT & RUN,S OSCEOLA ST / W BAYAUD AVE,-105.038499,39.714959,Careless Driving,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,Not Observed,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted
6,TRAF - ACCIDENT - HIT & RUN,300 BLOCK E 17TH AVE,-104.983103,39.743008,NaN,No Contributing Action,NaN,Passenger Car/Passenger Van,NaN,No Apparent Contributing Factor,Traveling Along Roadway Against Traffic (In or...,0.0,0.0,NaN,Non-Intersection,Dry,Daylight
7,TRAF - ACCIDENT - HIT & RUN,N OGDEN ST / E 11TH AVE,-104.975278,39.733689,Disregarded Stop Sign,No Contributing Action,Pickup Truck/Utility Van,Passenger Car/Passenger Van,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,At Intersection,Dry,Dark-Lighted
8,TRAF - ACCIDENT,N CENTRAL PARK BLVD / N VERBENA ST,-104.889926,39.751852,Careless Driving,Lane Violation,Passenger Car/Passenger Van,Passenger Car/Passenger Van,Aggressive Driving,Aggressive Driving,NaN,0.0,0.0,NaN,Intersection Related,Dry,Daylight
9,TRAF - ACCIDENT - HIT & RUN,I70 HWYWB / N NORTHFIELD QUEBEC ST,-104.903436,39.778421,Lane Violation,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,Not Observed,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Intersection Related,Dry,Dark-Lighted
10,TRAF - ACCIDENT - HIT & RUN,E 17TH AVE / N YOSEMITE ST,-104.884655,39.743783,Followed Too Closely,No Contributing Action,NaN,Passenger Car/Passenger Van,Not Observed,NaN,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dawn or Dusk
11,TRAF - ACCIDENT,S QUEBEC ST / E CHERRY CREEK S DR,-104.903509,39.684900,Followed Too Closely,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,Aggressive Driving,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,At Intersection,Dry,Daylight
12,TRAF - ACCIDENT - HIT & RUN,W 13TH AVE / N SPEER BLVD,-104.996475,39.736862,Careless Driving,No Contributing Action,Working Vehicle/Equipment,Other Vehicle Type (Describe in Narative),Aggressive Driving,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted
13,TRAF - ACCIDENT,1801 WEWATTA ST,-104.999962,39.755423,No Contributing Action,NaN,Pickup Truck/Utility Van,NaN,No Apparent Contributing Factor,NaN,NaN,0.0,0.0,NaN,Parking Lot,Dry,Dark-Lighted
14,TRAF - ACCIDENT - HIT & RUN,3144 N UMATILLA ST,-105.011670,39.761685,Careless Driving,NaN,Passenger Car/Passenger Van,NaN,NaN,NaN,NaN,0.0,0.0,NaN,Alley Related,Icy,Daylight
15,TRAF - ACCIDENT - HIT & RUN,E 53RD AVE / N CHAMBERS RD,-104.809755,39.790353,Careless Driving,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,Aggressive Driving,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,At Intersection,Dry,Dark-Lighted
16,TRAF - ACCIDENT - HIT & RUN,4547 E 16TH AVE,-104.934277,39.741633,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,NaN,NaN,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION
17,TRAF - ACCIDENT - HIT & RUN,300 S FEDERAL BLVD,-105.024750,39.710693,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,NaN,NaN,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION,UNDER INVESTIGATION
18,TRAF - ACCIDENT,"LAT:39°43'44.74""N LONG:104°58'39.34""W W 8TH AV...",-104.977595,39.729095,Failed to Yield ROW,NaN,Passenger Car/Passenger Van,NaN,Looked/Did Not See,NaN,NaN,0.0,0.0,Cross/Enter at Intersection,At Intersection,Dry,Dark-Lighted
19,TRAF - ACCIDENT - HIT & RUN,W 44TH AVE / N JULIAN ST,-105.031084,39.776695,Careless Driving,NaN,SUV,Passenger Car/Passenger Van,Aggressive Driving,NaN,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted

In [14]:
df.to_csv("data/interim/traffic_clean.csv")