In [1]:
from pathlib import Path
import os

PROJECT_ROOT = Path.cwd().parent

os.chdir(PROJECT_ROOT)
print("Project root:", PROJECT_ROOT)
print("Current working directory:", Path.cwd())

Project root: /Users/Local/REPOSITORIES/injury_risk_classifier
Current working directory: /Users/Local/REPOSITORIES/injury_risk_classifier

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from pathlib import Path
import os 

%load_ext autoreload
%autoreload 2

from src.explore_data import *

In [3]:
df = pd.read_csv("../injury_risk_classifier/data/interim/traffic_clean.csv")
df.head()

,top_traffic_accident_offense,incident_address,lon,lat,road_description,road_condition,light_condition,injured,tu1_vehicle_type_binned,tu2_vehicle_type_binned,tu1_driver_action_binned,tu2_driver_action_binned,tu1_human_factor_binned,tu2_human_factor_binned
0,TRAF - ACCIDENT,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,Non-Intersection,Dry,Daylight,0,pickup_or_utility_van,bus,no_action,no_action,no_apparent,no_apparent
1,TRAF - ACCIDENT,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,At Intersection,Dry,Daylight,0,passenger_car_or_van,suv,failure_to_yield,no_action,no_apparent,no_apparent
2,TRAF - ACCIDENT,I25 HWYSB / PARK AVEW,-104.994972,39.768330,Non-Intersection,Dry,Daylight,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,no_apparent,no_apparent
3,TRAF - ACCIDENT - POLICE,I25 HWYNB / 20TH ST,-105.004334,39.760949,Non-Intersection,Dry,Dark-Lighted,0,pickup_or_utility_van,passenger_car_or_van,aggressive_or_careless,no_action,aggressive_or_evading,no_apparent
4,TRAF - ACCIDENT - HIT & RUN,W 37TH AVE / N PECOS ST,-105.006450,39.768054,Non-Intersection,Dry,Dark-Lighted,0,unknown,passenger_car_or_van,unknown,unknown,unknown,unknown

In [4]:
df.columns

Index(['top_traffic_accident_offense', 'incident_address', 'lon', 'lat',
       'road_description', 'road_condition', 'light_condition', 'injured',
       'tu1_vehicle_type_binned', 'tu2_vehicle_type_binned',
       'tu1_driver_action_binned', 'tu2_driver_action_binned',
       'tu1_human_factor_binned', 'tu2_human_factor_binned'],
      dtype='str')

In [5]:
df.shape

(282358, 14)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 282358 entries, 0 to 282357
Data columns (total 14 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   top_traffic_accident_offense  282358 non-null  str
 1   incident_address              282358 non-null  str
 2   lon                           271203 non-null  float64
 3   lat                           271203 non-null  float64
 4   road_description              281783 non-null  str
 5   road_condition                281608 non-null  str
 6   light_condition               281695 non-null  str
 7   injured                       282358 non-null  int64
 8   tu1_vehicle_type_binned       282358 non-null  str
 9   tu2_vehicle_type_binned       282358 non-null  str
 10  tu1_driver_action_binned      282358 non-null  str
 11  tu2_driver_action_binned      282358 non-null  str
 12  tu1_human_factor_binned       282358 non-null  str
 13  tu2_human_factor_binned       282358 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 30.2 MB

In [7]:
df.head()

,top_traffic_accident_offense,incident_address,lon,lat,road_description,road_condition,light_condition,injured,tu1_vehicle_type_binned,tu2_vehicle_type_binned,tu1_driver_action_binned,tu2_driver_action_binned,tu1_human_factor_binned,tu2_human_factor_binned
0,TRAF - ACCIDENT,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,Non-Intersection,Dry,Daylight,0,pickup_or_utility_van,bus,no_action,no_action,no_apparent,no_apparent
1,TRAF - ACCIDENT,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,At Intersection,Dry,Daylight,0,passenger_car_or_van,suv,failure_to_yield,no_action,no_apparent,no_apparent
2,TRAF - ACCIDENT,I25 HWYSB / PARK AVEW,-104.994972,39.768330,Non-Intersection,Dry,Daylight,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,no_apparent,no_apparent
3,TRAF - ACCIDENT - POLICE,I25 HWYNB / 20TH ST,-105.004334,39.760949,Non-Intersection,Dry,Dark-Lighted,0,pickup_or_utility_van,passenger_car_or_van,aggressive_or_careless,no_action,aggressive_or_evading,no_apparent
4,TRAF - ACCIDENT - HIT & RUN,W 37TH AVE / N PECOS ST,-105.006450,39.768054,Non-Intersection,Dry,Dark-Lighted,0,unknown,passenger_car_or_van,unknown,unknown,unknown,unknown

In [8]:
df.describe(include="all")

,top_traffic_accident_offense,incident_address,lon,lat,road_description,road_condition,light_condition,injured,tu1_vehicle_type_binned,tu2_vehicle_type_binned,tu1_driver_action_binned,tu2_driver_action_binned,tu1_human_factor_binned,tu2_human_factor_binned
count,282358,282358,271203.000000,271203.000000,281783,281608,281695,282358.000000,282358,282358,282358,282358,282358,282358
unique,6,52971,NaN,NaN,24,28,10,NaN,12,12,10,10,12,12
top,TRAF - ACCIDENT,I25 HWYNB / W 6TH AVE,NaN,NaN,NON INTERSECTION,DRY,DAY LIGHT,NaN,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,no_apparent,no_apparent
freq,181919,1981,NaN,NaN,82144,169737,138562,NaN,132033,135200,104802,153625,94872,218879
mean,NaN,NaN,-104.958343,39.732038,NaN,NaN,NaN,0.023187,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.069833,0.041531,NaN,NaN,NaN,0.150497,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,-105.206197,39.614406,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,-105.004766,39.705704,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,-104.977587,39.738276,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,-104.918259,39.762007,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,-104.600000,39.904310,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.isna().mean().sort_values(ascending=False).head(30)

lon                             0.039507
lat                             0.039507
road_condition                  0.002656
light_condition                 0.002348
road_description                0.002036
top_traffic_accident_offense    0.000000
incident_address                0.000000
injured                         0.000000
tu1_vehicle_type_binned         0.000000
tu2_vehicle_type_binned         0.000000
tu1_driver_action_binned        0.000000
tu2_driver_action_binned        0.000000
tu1_human_factor_binned         0.000000
tu2_human_factor_binned         0.000000
dtype: float64

In [12]:
df["injured"].value_counts(normalize=False)

injured
0    275811
1      6547
Name: count, dtype: int64

In [13]:
df.head(10)

,top_traffic_accident_offense,incident_address,lon,lat,road_description,road_condition,light_condition,injured,tu1_vehicle_type_binned,tu2_vehicle_type_binned,tu1_driver_action_binned,tu2_driver_action_binned,tu1_human_factor_binned,tu2_human_factor_binned
0,TRAF - ACCIDENT,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,Non-Intersection,Dry,Daylight,0,pickup_or_utility_van,bus,no_action,no_action,no_apparent,no_apparent
1,TRAF - ACCIDENT,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,At Intersection,Dry,Daylight,0,passenger_car_or_van,suv,failure_to_yield,no_action,no_apparent,no_apparent
2,TRAF - ACCIDENT,I25 HWYSB / PARK AVEW,-104.994972,39.768330,Non-Intersection,Dry,Daylight,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,no_apparent,no_apparent
3,TRAF - ACCIDENT - POLICE,I25 HWYNB / 20TH ST,-105.004334,39.760949,Non-Intersection,Dry,Dark-Lighted,0,pickup_or_utility_van,passenger_car_or_van,aggressive_or_careless,no_action,aggressive_or_evading,no_apparent
4,TRAF - ACCIDENT - HIT & RUN,W 37TH AVE / N PECOS ST,-105.006450,39.768054,Non-Intersection,Dry,Dark-Lighted,0,unknown,passenger_car_or_van,unknown,unknown,unknown,unknown
5,TRAF - ACCIDENT - HIT & RUN,S OSCEOLA ST / W BAYAUD AVE,-105.038499,39.714959,Non-Intersection,Dry,Dark-Lighted,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,no_action,unknown,no_apparent
6,TRAF - ACCIDENT - HIT & RUN,300 BLOCK E 17TH AVE,-104.983103,39.743008,Non-Intersection,Dry,Daylight,0,unknown,passenger_car_or_van,unknown,no_action,unknown,no_apparent
7,TRAF - ACCIDENT - HIT & RUN,N OGDEN ST / E 11TH AVE,-104.975278,39.733689,At Intersection,Dry,Dark-Lighted,0,pickup_or_utility_van,passenger_car_or_van,failure_to_obey,no_action,no_apparent,no_apparent
8,TRAF - ACCIDENT,N CENTRAL PARK BLVD / N VERBENA ST,-104.889926,39.751852,Intersection Related,Dry,Daylight,0,passenger_car_or_van,passenger_car_or_van,aggressive_or_careless,lane_or_position,aggressive_or_evading,aggressive_or_evading
9,TRAF - ACCIDENT - HIT & RUN,I70 HWYWB / N NORTHFIELD QUEBEC ST,-104.903436,39.778421,Intersection Related,Dry,Dark-Lighted,0,passenger_car_or_van,passenger_car_or_van,lane_or_position,no_action,unknown,no_apparent

In [14]:
df.isna().sum()

top_traffic_accident_offense        0
incident_address                    0
lon                             11155
lat                             11155
road_description                  575
road_condition                    750
light_condition                   663
injured                             0
tu1_vehicle_type_binned             0
tu2_vehicle_type_binned             0
tu1_driver_action_binned            0
tu2_driver_action_binned            0
tu1_human_factor_binned             0
tu2_human_factor_binned             0
dtype: int64