In [1]:
from pathlib import Path
import os

PROJECT_ROOT = Path.cwd().parent

os.chdir(PROJECT_ROOT)
print("Project root:", PROJECT_ROOT)
print("Current working directory:", Path.cwd())

Project root: /Users/Local/REPOSITORIES/injury_risk_classifier
Current working directory: /Users/Local/REPOSITORIES/injury_risk_classifier

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from pathlib import Path
import os 

%load_ext autoreload
%autoreload 2

from src.explore_data import *

In [3]:
df = pd.read_csv("../injury_risk_classifier/data/interim/traffic_clean.csv")
df.head()

,Unnamed: 0,top_traffic_accident_offense,incident_address,geo_lon,geo_lat,tu1_driver_action,tu2_driver_action,tu1_vehicle_type,tu2_vehicle_type,tu1_driver_humancontribfactor,tu2_driver_humancontribfactor,tu1_pedestrian_action,seriously_injured,fatalities,tu2_pedestrian_action,road_description,road_condition,light_condition
0,0,TRAF - ACCIDENT,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,No Contributing Action,No Contributing Action,pickup truck/utility van,transit bus,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight
1,1,TRAF - ACCIDENT,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,Failed to Yield ROW,No Contributing Action,passenger car/passenger van,suv,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,At Intersection,Dry,Daylight
2,2,TRAF - ACCIDENT,I25 HWYSB / PARK AVEW,-104.994972,39.768330,Followed Too Closely,No Contributing Action,passenger car/passenger van,passenger car/passenger van,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight
3,3,TRAF - ACCIDENT - POLICE,I25 HWYNB / 20TH ST,-105.004334,39.760949,Followed Too Closely,No Contributing Action,pickup truck/utility van,passenger car/passenger van,Aggressive Driving,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted
4,4,TRAF - ACCIDENT - HIT & RUN,W 37TH AVE / N PECOS ST,-105.006450,39.768054,NaN,NaN,unknown (hit and run only),passenger car/passenger van,NaN,NaN,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted

In [4]:
df.columns

Index(['Unnamed: 0', 'top_traffic_accident_offense', 'incident_address',
       'geo_lon', 'geo_lat', 'tu1_driver_action', 'tu2_driver_action',
       'tu1_vehicle_type', 'tu2_vehicle_type', 'tu1_driver_humancontribfactor',
       'tu2_driver_humancontribfactor', 'tu1_pedestrian_action',
       'seriously_injured', 'fatalities', 'tu2_pedestrian_action',
       'road_description', 'road_condition', 'light_condition'],
      dtype='str')

In [5]:
df.shape

(282358, 18)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 282358 entries, 0 to 282357
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     282358 non-null  int64
 1   top_traffic_accident_offense   282358 non-null  str
 2   incident_address               282358 non-null  str
 3   geo_lon                        271203 non-null  float64
 4   geo_lat                        271203 non-null  float64
 5   tu1_driver_action              268935 non-null  str
 6   tu2_driver_action              267212 non-null  str
 7   tu1_vehicle_type               273377 non-null  str
 8   tu2_vehicle_type               263372 non-null  str
 9   tu1_driver_humancontribfactor  266545 non-null  str
 10  tu2_driver_humancontribfactor  268176 non-null  str
 11  tu1_pedestrian_action          204927 non-null  str
 12  seriously_injured              280738 non-null  float64
 13  fatalities                     280738 non-null  float64
 14  tu2_pedestrian_action          205715 non-null  str
 15  road_description               281783 non-null  str
 16  road_condition                 281608 non-null  str
 17  light_condition                281695 non-null  str
dtypes: float64(4), int64(1), str(13)
memory usage: 38.8 MB

In [7]:
df.head()

,Unnamed: 0,top_traffic_accident_offense,incident_address,geo_lon,geo_lat,tu1_driver_action,tu2_driver_action,tu1_vehicle_type,tu2_vehicle_type,tu1_driver_humancontribfactor,tu2_driver_humancontribfactor,tu1_pedestrian_action,seriously_injured,fatalities,tu2_pedestrian_action,road_description,road_condition,light_condition
0,0,TRAF - ACCIDENT,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,No Contributing Action,No Contributing Action,pickup truck/utility van,transit bus,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight
1,1,TRAF - ACCIDENT,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,Failed to Yield ROW,No Contributing Action,passenger car/passenger van,suv,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,At Intersection,Dry,Daylight
2,2,TRAF - ACCIDENT,I25 HWYSB / PARK AVEW,-104.994972,39.768330,Followed Too Closely,No Contributing Action,passenger car/passenger van,passenger car/passenger van,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight
3,3,TRAF - ACCIDENT - POLICE,I25 HWYNB / 20TH ST,-105.004334,39.760949,Followed Too Closely,No Contributing Action,pickup truck/utility van,passenger car/passenger van,Aggressive Driving,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted
4,4,TRAF - ACCIDENT - HIT & RUN,W 37TH AVE / N PECOS ST,-105.006450,39.768054,NaN,NaN,unknown (hit and run only),passenger car/passenger van,NaN,NaN,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted

In [8]:
df.describe(include="all")

,Unnamed: 0,top_traffic_accident_offense,incident_address,geo_lon,geo_lat,tu1_driver_action,tu2_driver_action,tu1_vehicle_type,tu2_vehicle_type,tu1_driver_humancontribfactor,tu2_driver_humancontribfactor,tu1_pedestrian_action,seriously_injured,fatalities,tu2_pedestrian_action,road_description,road_condition,light_condition
count,282358.000000,282358,282358,271203.000000,271203.000000,268935,267212,273377,263372,266545,268176,204927,280738.000000,280738.000000,205715,281783,281608,281695
unique,NaN,6,52971,NaN,NaN,64,47,32,32,46,39,34,NaN,NaN,38,24,28,10
top,NaN,TRAF - ACCIDENT,I25 HWYNB / W 6TH AVE,NaN,NaN,CARELESS DRIVING,OTHER,passenger car/van,passenger car/van,NO APPARENT,NO APPARENT,OTHER,NaN,NaN,OTHER,NON INTERSECTION,DRY,DAY LIGHT
freq,NaN,181919,1981,NaN,NaN,41447,91557,96849,97377,78494,158553,127464,NaN,NaN,126836,82144,169737,138562
mean,141178.500000,NaN,NaN,-104.958343,39.732038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.024632,0.002483,NaN,NaN,NaN,NaN
std,81509.877991,NaN,NaN,0.069833,0.041531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.180758,0.052483,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,-105.206197,39.614406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,70589.250000,NaN,NaN,-105.004766,39.705704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,141178.500000,NaN,NaN,-104.977587,39.738276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN
75%,211767.750000,NaN,NaN,-104.918259,39.762007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN
max,282357.000000,NaN,NaN,-104.600000,39.904310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,3.000000,NaN,NaN,NaN,NaN

In [9]:
df.isna().mean().sort_values(ascending=False).head(30)

tu1_pedestrian_action            0.274230
tu2_pedestrian_action            0.271439
tu2_vehicle_type                 0.067241
tu1_driver_humancontribfactor    0.056003
tu2_driver_action                0.053641
tu2_driver_humancontribfactor    0.050227
tu1_driver_action                0.047539
geo_lon                          0.039507
geo_lat                          0.039507
tu1_vehicle_type                 0.031807
fatalities                       0.005737
seriously_injured                0.005737
road_condition                   0.002656
light_condition                  0.002348
road_description                 0.002036
top_traffic_accident_offense     0.000000
incident_address                 0.000000
Unnamed: 0                       0.000000
dtype: float64

In [10]:
df["injury_or_fatality"] = (
    (df["seriously_injured"] > 0) |
    (df["fatalities"] > 0)
)

df["injury_or_fatality"].value_counts(normalize=True)

injury_or_fatality
False    0.976813
True     0.023187
Name: proportion, dtype: float64