### Set up

In [1]:
from pathlib import Path
import sys

def find_project_root(marker="README.md"):
    current = Path.cwd().resolve()
    for parent in [current, *current.parents]:
        if (parent / marker).exists():
            return parent
    raise FileNotFoundError(f"Could not find project root with marker: {marker}")

PROJECT_ROOT = find_project_root()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(f"Project root: {PROJECT_ROOT}")

Project root: /Users/Local/REPOSITORIES/injury_risk_classifier

In [4]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt

from src.cleaning_and_features import features
from src.cleaning_and_features import clean
from src import audit
from src.cleaning_and_features import geo

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
DATA_PATH = PROJECT_ROOT / "data" / "interim" / "traffic_clean.csv"

df = pd.read_csv(DATA_PATH)

df.shape

(282290, 20)

# Features

## Vehicle type difference

In [6]:
df["vehicle_type_match"] = df.apply(features.vehicle_match, axis=1)

In [7]:
df = features.vehicle_sizes(df)

In [8]:
features.size_relation(df)

,top_traffic_accident_offense,first_occurrence_date,incident_address,lon,lat,tu1_travel_direction,tu2_travel_direction,road_description,road_condition,light_condition,...,tu1_driver_action_binned,tu2_driver_action_binned,tu1_human_factor_binned,tu2_human_factor_binned,vehicle_type_match,tu1_vehicle_size,tu2_vehicle_size,vehicle_size_diff,abs_vehicle_size_diff,vehicle_size_relation
0,TRAF - ACCIDENT,2.459922e+06,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,north,north,non-intersection,dry,daylight,...,no_action,no_action,no_apparent,no_apparent,different,3.0,4.0,-1.0,1.0,vehicle_2_larger
1,TRAF - ACCIDENT,2.459925e+06,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,south,east,at intersection,dry,daylight,...,failure_to_yield,no_action,no_apparent,no_apparent,different,2.0,3.0,-1.0,1.0,vehicle_2_larger
2,TRAF - ACCIDENT,2.459925e+06,I25 HWYSB / PARK AVEW,-104.994972,39.768330,south,south,non-intersection,dry,daylight,...,aggressive_or_careless,no_action,no_apparent,no_apparent,same,2.0,2.0,0.0,0.0,same_size
3,TRAF - ACCIDENT - POLICE,2.459922e+06,I25 HWYNB / 20TH ST,-105.004334,39.760949,south,south,non-intersection,dry,dark-lighted,...,aggressive_or_careless,no_action,aggressive_or_evading,no_apparent,different,3.0,2.0,1.0,1.0,vehicle_1_larger
4,TRAF - ACCIDENT - HIT & RUN,2.459922e+06,W 37TH AVE / N PECOS ST,-105.006450,39.768054,NaN,NaN,non-intersection,dry,dark-lighted,...,unknown,unknown,unknown,unknown,unknown,NaN,2.0,NaN,NaN,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282285,TRAF - ACCIDENT,2.459920e+06,I25 HWYSB / W 23RD AVE,-105.016793,39.751285,south,south,at intersection,dry,daylight,...,lane_or_position,no_action,distracted,no_apparent,same,2.0,2.0,0.0,0.0,same_size
282286,TRAF - ACCIDENT - HIT & RUN,2.459942e+06,I70 HWYWB / N MONACO ST,-104.912882,39.778408,west,west,non-intersection,dry,daylight,...,aggressive_or_careless,no_action,aggressive_or_evading,no_apparent,different,3.0,3.0,0.0,0.0,same_size
282287,TRAF - ACCIDENT,2.459942e+06,50 BLOCK N HOLLY ST,-104.922176,39.717045,north,north,non-intersection,wet,daylight,...,aggressive_or_careless,no_action,no_apparent,no_apparent,different,2.0,3.0,-1.0,1.0,vehicle_2_larger
282288,TRAF - ACCIDENT - HIT & RUN,2.459945e+06,20TH ST / ARAPAHOE ST,-104.990832,39.751590,west,west,at intersection,dry,dark-lighted,...,lane_or_position,no_action,no_apparent,no_apparent,same,2.0,2.0,0.0,0.0,same_size
282289,TRAF - ACCIDENT - HIT & RUN,2.459944e+06,5190 N GRAY ST,-105.060105,39.790885,east,NaN,non-intersection,icy w/visible icy road treatment,daylight,...,speed_related,unknown,no_apparent,unknown,unknown,NaN,NaN,NaN,NaN,unknown

## Actions by vehicle size

In [9]:
features.vehicle_size_actions(df)

,top_traffic_accident_offense,first_occurrence_date,incident_address,lon,lat,tu1_travel_direction,tu2_travel_direction,road_description,road_condition,light_condition,...,tu1_human_factor_binned,tu2_human_factor_binned,vehicle_type_match,tu1_vehicle_size,tu2_vehicle_size,vehicle_size_diff,abs_vehicle_size_diff,vehicle_size_relation,smaller_vehicle_action,larger_vehicle_action
0,TRAF - ACCIDENT,2.459922e+06,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,north,north,non-intersection,dry,daylight,...,no_apparent,no_apparent,different,3.0,4.0,-1.0,1.0,vehicle_2_larger,no_action,no_action
1,TRAF - ACCIDENT,2.459925e+06,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,south,east,at intersection,dry,daylight,...,no_apparent,no_apparent,different,2.0,3.0,-1.0,1.0,vehicle_2_larger,failure_to_yield,no_action
2,TRAF - ACCIDENT,2.459925e+06,I25 HWYSB / PARK AVEW,-104.994972,39.768330,south,south,non-intersection,dry,daylight,...,no_apparent,no_apparent,same,2.0,2.0,0.0,0.0,same_size,same_size,same_size
3,TRAF - ACCIDENT - POLICE,2.459922e+06,I25 HWYNB / 20TH ST,-105.004334,39.760949,south,south,non-intersection,dry,dark-lighted,...,aggressive_or_evading,no_apparent,different,3.0,2.0,1.0,1.0,vehicle_1_larger,no_action,aggressive_or_careless
4,TRAF - ACCIDENT - HIT & RUN,2.459922e+06,W 37TH AVE / N PECOS ST,-105.006450,39.768054,NaN,NaN,non-intersection,dry,dark-lighted,...,unknown,unknown,unknown,NaN,2.0,NaN,NaN,unknown,unknown,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282285,TRAF - ACCIDENT,2.459920e+06,I25 HWYSB / W 23RD AVE,-105.016793,39.751285,south,south,at intersection,dry,daylight,...,distracted,no_apparent,same,2.0,2.0,0.0,0.0,same_size,same_size,same_size
282286,TRAF - ACCIDENT - HIT & RUN,2.459942e+06,I70 HWYWB / N MONACO ST,-104.912882,39.778408,west,west,non-intersection,dry,daylight,...,aggressive_or_evading,no_apparent,different,3.0,3.0,0.0,0.0,same_size,same_size,same_size
282287,TRAF - ACCIDENT,2.459942e+06,50 BLOCK N HOLLY ST,-104.922176,39.717045,north,north,non-intersection,wet,daylight,...,no_apparent,no_apparent,different,2.0,3.0,-1.0,1.0,vehicle_2_larger,aggressive_or_careless,no_action
282288,TRAF - ACCIDENT - HIT & RUN,2.459945e+06,20TH ST / ARAPAHOE ST,-104.990832,39.751590,west,west,at intersection,dry,dark-lighted,...,no_apparent,no_apparent,same,2.0,2.0,0.0,0.0,same_size,same_size,same_size
282289,TRAF - ACCIDENT - HIT & RUN,2.459944e+06,5190 N GRAY ST,-105.060105,39.790885,east,NaN,non-intersection,icy w/visible icy road treatment,daylight,...,no_apparent,unknown,unknown,NaN,NaN,NaN,NaN,unknown,unknown,unknown

## sidenote - date types

In [10]:
df = clean.split_datetime(df, "first_occurrence_date")

df = features.create_time_variables(df)

In [11]:
df[[
    "first_occurrence_date",
    "datetime",
    "date",
    "time",
    "hour",
    "is_night",
    "evening_rush",
    "morning_rush"
]].sample(20)

,first_occurrence_date,datetime,date,time,hour,is_night,evening_rush,morning_rush
30780,2.457478e+06,2016-03-30 10:00:59.999983012,2016-03-30,10:00:59,10,False,False,False
266827,2.460258e+06,2023-11-09 19:50:00.000008943,2023-11-09,19:50:00,19,False,False,False
58587,2.457467e+06,2016-03-19 11:24:00.000008043,2016-03-19,11:24:00,11,False,False,False
256640,2.460999e+06,2025-11-19 16:03:00.000016096,2025-11-19,16:03:00,16,False,True,False
76290,2.457900e+06,2017-05-26 10:37:00.000015196,2017-05-26,10:37:00,10,False,False,False
107114,2.458401e+06,2018-10-09 11:01:00.000009834,2018-10-09,11:01:00,11,False,False,False
195013,2.458818e+06,2019-11-30 21:09:00.000008043,2019-11-30,21:09:00,21,True,False,False
178070,2.457078e+06,2015-02-24 11:45:00.000013415,2015-02-24,11:45:00,11,False,False,False
120074,2.456880e+06,2014-08-10 20:18:59.999985694,2014-08-10,20:18:59,20,True,False,False
154657,2.456658e+06,2013-12-31 16:02:00.000019668,2013-12-31,16:02:00,16,False,True,False
122678,2.456732e+06,2014-03-15 20:00:00.000013415,2014-03-15,20:00:00,20,True,False,False
195911,2.458829e+06,2019-12-11 11:59:00.000003572,2019-12-11,11:59:00,11,False,False,False
28881,2.459238e+06,2021-01-23 14:46:00.000009834,2021-01-23,14:46:00,14,False,False,False
86685,2.458096e+06,2017-12-08 17:22:00.000015196,2017-12-08,17:22:00,17,False,True,False
191809,2.458632e+06,2019-05-28 15:22:59.999998209,2019-05-28,15:22:59,15,False,False,False
235771,2.459614e+06,2022-02-03 17:01:00.000009834,2022-02-03,17:01:00,17,False,True,False
135771,2.456429e+06,2013-05-16 07:16:00.000009834,2013-05-16,07:16:00,7,False,False,True
54071,2.457752e+06,2016-12-29 14:19:59.999982121,2016-12-29,14:19:59,14,False,False,False
185730,2.458631e+06,2019-05-27 16:29:00.000003572,2019-05-27,16:29:00,16,False,True,False
136094,2.456605e+06,2013-11-08 15:55:00.000004471,2013-11-08,15:55:00,15,False,False,False

In [12]:
timecheck = ((df["is_night"] == "True") & 
             ((df["morning_rush"] == "True") | (df["evening_rush"] == "True"))).sum()
timecheck

np.int64(0)

In [13]:
df = clean.convert_column_types(
    df,
    bool_cols=["injured"],
    int_cols=["tu1_vehicle_size", "tu2_vehicle_size",
              "vehicle_size_diff", "abs_vehicle_size_diff"],
    float_cols=["lat", "lon"],
    category_cols=["tu1_vehicle_type_binned", "tu2_vehicle_type_binned", 
                   "light_condition", "road_condition"],
    string_cols=["incident_address", "top_traffic_accident_offense"]
)

df.dtypes

top_traffic_accident_offense            string
first_occurrence_date                  float64
incident_address                        string
lon                                    float64
lat                                    float64
tu1_travel_direction                       str
tu2_travel_direction                       str
road_description                           str
road_condition                        category
light_condition                       category
datetime                        datetime64[ns]
date                                    object
time                                       str
injured                                boolean
tu1_vehicle_type_binned               category
tu2_vehicle_type_binned               category
tu1_driver_action_binned                   str
tu2_driver_action_binned                   str
tu1_human_factor_binned                    str
tu2_human_factor_binned                    str
vehicle_type_match                         str
tu1_vehicle_size                         Int64
tu2_vehicle_size                         Int64
vehicle_size_diff                        Int64
abs_vehicle_size_diff                    Int64
vehicle_size_relation                      str
smaller_vehicle_action                     str
larger_vehicle_action                      str
day_of_week                              int32
weekend                                   bool
weekday                                   bool
month                                    int32
hour                                     int32
is_night                                  bool
morning_rush                              bool
evening_rush                              bool
dtype: object

## Temporal features

In [14]:
df = features.create_time_variables(df)

## Presence

In [15]:
df = features.presence(df)

In [16]:
df["light_condition"] = (
    df["light_condition"]
    .str.replace(" ", "", regex=False)
)

## Highway

In [17]:
df = features.create_highway_indicator(df)

In [18]:
df["is_highway"].value_counts(normalize=True)

is_highway
False    0.807368
True     0.192632
Name: proportion, dtype: Float64

In [19]:
df.loc[
    df["is_highway"],
    ["incident_address", "is_highway"]
].sample(20, random_state=67)

                           incident_address  is_highway
77865                 W 6TH AVE / I25 HWYSB        True
242298                I25 HWYNB / W 6TH AVE        True
87936   N NORTHFIELD QUEBEC ST / I270 HWYEB        True
133257  SB E470 TO EB PENA RAMP / PENA BLVD        True
132694                          I225 HWY_SB        True
8612               W COLFAX AVE / I25 HWYNB        True
245340               I225 HWYSB / I25 HWYSB        True
189196             I25 HWYSB / N SPEER BLVD        True
98346        E 56TH AVE / PENA BLVD INBOUND        True
68661                 I25 HWYSB / I70 HWYEB        True
31983                I70 HWYWB / N PECOS ST        True
206225                  I25 HWYNB / 20TH ST        True
74519                 I25 HWYNB / W 8TH AVE        True
73943         7900 BLOCK PENA BLVD OUTBOUND        True
237055                  I25 HWYNB / 20TH ST        True
88560                I70 HWYWB / N PECOS ST        True
197825              I70 HWYEB / N PEORIA ST        True
201905                W 6TH AVE / I25 HWYSB        True
215052          I70 HWYEB / N COLORADO BLVD        True
251926                I25 HWYNB / W 8TH AVE        True

## speedlimit with coordinates

https://opendata-geospatialdenver.hub.arcgis.com/datasets/geospatialDenver::street-centerlines/about

Which road line is closest to each crash point?

In [20]:
roads_gdf = gpd.read_file("/Users/Local/REPOSITORIES/injury_risk_classifier/data/raw/ODC_TRANS_STREET_L_5394477846909849941.geojson")

In [21]:
roads_gdf.head()

,OBJECTID,FNODE,TNODE,STREETID,MASTERID,L_F_ADD,L_T_ADD,R_F_ADD,R_T_ADD,PREFIX,...,SNOWROUTE_ID,PRIORITY,RSPROUTE,PCI,created_user,created_date,last_edited_user,last_edited_date,GlobalID,geometry
0,3339107,11606.0,11724,830.0,10249,1600.0,1698.0,1601.0,1699.0,S,...,40101.0,Super A,NaN,NaN,STREETS,"Thu, 08 Jun 2017 00:00:00 GMT",220181,"Mon, 28 Apr 2025 15:21:34 GMT",00a43daa-5837-4f2b-b697-a2bc8109a83b,"LINESTRING (-104.94065 39.68749, -104.94069 39..."
1,3339108,19737.0,19728,3.0,30725,0.0,0.0,22878.0,22948.0,E,...,NaN,NaN,NaN,NaN,STREETS,"Thu, 17 Sep 2009 00:00:00 GMT",137161,"Wed, 17 Dec 2025 20:35:22 GMT",00bb22aa-fe8e-40d7-9ef3-0caaf41d74ed,"LINESTRING (-104.7206 39.8127, -104.7206 39.81..."
2,3339109,4221.0,4220,284.0,13503,4301.0,4399.0,4300.0,4398.0,E,...,NaN,NaN,RS206,NaN,STREETS,"Wed, 02 May 2018 00:00:00 GMT",220181,"Mon, 28 Apr 2025 15:21:34 GMT",011ccd08-892c-4f0b-a0f0-d5e12ea1bd93,"LINESTRING (-104.9372 39.76016, -104.93666 39...."
3,3339110,2910.0,2905,116.0,1276,3901.0,3999.0,3900.0,3998.0,E,...,30704.0,A,NaN,NaN,STREETS,"Wed, 06 Feb 2008 00:00:00 GMT",220181,"Mon, 28 Apr 2025 15:21:34 GMT",0124b7bc-0346-4071-80fe-ff0d77ac9c2f,"LINESTRING (-104.94169 39.77288, -104.94099 39..."
4,3339111,4206.0,3985,282.0,13817,3001.0,3199.0,3000.0,3198.0,N,...,NaN,NaN,RS206,NaN,STREETS,"Thu, 17 Jun 2004 00:00:00 GMT",220181,"Mon, 28 Apr 2025 15:21:34 GMT",017b36bd-337b-45f2-b3ec-e39f34a0b48b,"LINESTRING (-104.92111 39.76018, -104.92111 39..."

In [22]:
roads_gdf = roads_gdf[["SPEEDLIMIT", "FULLNAME", "geometry"]]

In [23]:
crashes_gdf = geo.make_crash_points(df)

In [24]:
crashes_with_roads = geo.convert_to_meters(crashes_gdf, roads_gdf)

In [25]:
crashes_with_roads = geo.match_quality(crashes_with_roads, "distance_to_road_m")

In [26]:
crashes_with_roads = crashes_with_roads.rename(columns={
    "SPEEDLIMIT": "speed_limit",
    "FULLNAME":"road_name"
})

In [27]:
crashes_with_roads = geo.add_speed_limit_features(crashes_with_roads, "speed_limit")

In [28]:
cols_to_check = [
    "road_name",
    "incident_address",
    "lat",
    "lon",
    "distance_to_road_m",
    "speed_limit"
]

crashes_with_roads[cols_to_check].sample(30, random_state=67)

,road_name,incident_address,lat,lon,distance_to_road_m,speed_limit
108692,N WASHINGTON ST,E COLFAX AVE / N WASHINGTON ST,39.740016,-104.978744,0.078489,30.0
110393,E 13TH AVE,2100 BLOCK E 13TH AVE,39.736747,-104.961949,7.768016,30.0
27435,N FEDERAL BLVD,EB 6TH TO FEDERAL RAMP / N FEDERAL BLVD,39.725140,-105.025029,0.092746,35.0
280437,E 40TH AVE,16221 E 40TH AVE,39.773353,-104.798851,50.846675,25.0
82052,N BLACKHAWK WAY,4800 BLOCK N CROWN BLVD,39.782263,-104.832539,21.961318,25.0
19898,INTERSTATE 25,I25 HWYSB / N SPEER BLVD,39.755367,-105.012696,0.029676,55.0
262427,E ALAMEDA AVE,E ALAMEDA AVE / S IVY ST,39.711269,-104.921122,0.022562,35.0
142087,E HAMPDEN AVE,4900 BLOCK E HAMPDEN AVE,39.652974,-104.929934,7.918403,40.0
65833,W 31ST AVE,W 31ST AVE / N FOX ST,39.760793,-104.995428,0.024567,25.0
48439,CURTIS ST,19TH ST / CURTIS ST,39.750005,-104.991199,0.110110,25.0
275273,LEVEL 5 RD,8400 PENA BLVD,39.849292,-104.673812,90.834626,25.0
24307,INTERSTATE 25,I70 HWYEB / I25 HWYNB,39.780043,-104.989195,0.028309,55.0
14639,W COLFAX AVE,I25 HWYNB / W COLFAX AVE,39.740435,-105.013966,0.056079,40.0
55785,N FEDERAL BLVD,W 6TH AVE / N FEDERAL BLVD,39.725426,-105.025137,0.089491,35.0
45895,LEVEL 5 RD,8400 PENA BLVD,39.849292,-104.673812,90.834626,25.0
192743,N BRIGHTON BLVD,38TH ST / N BRIGHTON BLVD,39.772960,-104.975428,0.024469,30.0
181503,E COLFAX AVE,E COLFAX AVE / N JASMINE ST,39.740144,-104.918775,0.275890,35.0
10109,E 26TH AVE,E 26TH AVE / N YORK ST,39.754466,-104.959761,0.150742,30.0
244418,N SHERIDAN BLVD,35 N SHERIDAN BLVD,39.717254,-105.053276,0.160419,35.0
199118,E 14TH AVE,E 14TH AVE / N WILLIAMS ST,39.738402,-104.966001,0.075042,30.0
59955,INTERSTATE 25,I25 HWYNB / W COLFAX AVE,39.740326,-105.013949,0.135799,55.0
26075,W 50TH AVE,4500 BLOCK W 50TH AVE,39.787366,-105.045669,7.767518,25.0
260602,E VIRGINIA AVE,500 BLOCK S PEARL ST,39.707369,-104.980124,14.015754,25.0
276576,E 1ST AVE,N COLORADO BLVD / E 1ST AVE,39.717794,-104.940712,0.019726,25.0
70496,PARK AVE W,1800 BLOCK PARK AVEW,39.759022,-104.993324,7.872829,30.0
158410,PENA BLVD INBOUND,25000 BLOCK PENA BLVD INBOUND,39.833395,-104.695354,7.731466,65.0
89062,INTERSTATE 25,I25 HWYSB / I225 HWYNB,39.634278,-104.907099,0.087401,55.0
51681,WAZEE ST,18TH ST / WAZEE ST,39.753083,-104.997625,0.187410,25.0
160170,N HAVANA ST,I70 HWYEB / N HAVANA ST,39.775622,-104.865743,0.054243,40.0
5531,N FEDERAL BLVD,3100 BLOCK N FEDERAL BLVD,39.761438,-105.025146,7.424164,35.0

In [29]:
crashes_with_roads = crashes_with_roads.drop(columns=["incident_address", "geometry"])

processed_data_sample = crashes_with_roads.sample(50, random_state=67)

In [30]:
crashes_with_roads.shape

(271585, 50)

In [31]:
# sample pushed to repo
processed_data_sample.to_csv("processed_data_sample.csv", 
                             index = False)

# saved on local machine 
crashes_with_roads.to_parquet("crashes_model_data.parquet",
                                 index = False)